ExcellentMarketResearch/Areas/Admin/Controllers/PublisherController.cs
using ExcellentMarketResearch.Areas.Admin.Models.DAL;
using ExcellentMarketResearch.Areas.Admin.Models.ViewModel;
using ExcellentMarketResearch.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ExcellentMarketResearch.Areas.Admin.Models;

namespace ExcellentMarketResearch.Areas.Admin.Controllers
{
    public class PublisherController : Controller
    {
        //
        // GET: /Admin/Publisher/
        public ActionResult Index()
        {
            return View();
        }
        private PublisherRepository _ObjPublisherRepository;
        public PublisherController()
        {
            _ObjPublisherRepository = new PublisherRepository();
        }

        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherIndex()
        {
            // var publisher = db.PublisherMasters.ToList();

            return View(_ObjPublisherRepository.GetPublisher());
        }

        [HttpGet]
        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherCreate()
        {
            return View();
        }

        [HttpPost]
        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherCreate(PublisherVM pub)
        {
            _ObjPublisherRepository.InsertPublisher(pub);
            return RedirectToAction("PublisherIndex");
        }

        [HttpGet]
        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherEdit(int id)
        {
            return View(_ObjPublisherRepository.GetById(id));
        }
        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherEdit(PublisherVM pub)
        {
            _ObjPublisherRepository.PublisherEdit(pub);
            return RedirectToAction("PublisherIndex");
        }
        [CustomAuthentication("ReportUploader", "Create,Edit,Delete")]
        public ActionResult PublisherDetails(int id)
        {
            return View(_ObjPublisherRepository.GetById(id));
        }

        public ActionResult PublisherDelete(int id)
        {
            return View(_ObjPublisherRepository.GetById(id));
        }
        [ActionName("PublisherDelete")]
        public ActionResult PublisherDelete1(int id)
        {
            _ObjPublisherRepository.DeletePublisher(id);
            return RedirectToAction("PublisherIndex"); 
        }
    }
}

ExcellentMarketResearch/Areas/Admin/Views/Publisher/PublisherCreate.cshtml
@model ExcellentMarketResearch.Areas.Admin.Models.ViewModel.PublisherVM
s@{
    ViewBag.Title = "PublisherCreate";
}
<h2 style="font-family:Calibri;text-align:center">Publisher Master</h2>
<style type="text/css">
    .table tbody tr td {
        border-top: none;
    }
    .field-validation-error {
        color:red;
    }
</style>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="table" style="text-align:right; width: 80%;margin-top:50px">
            <tr>
                <td>
                    @Html.Label("Company Name")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherName)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateCompanyName
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    @Html.Label("Contact Name")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ContactName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Contact Number")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherContactNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherContactNumber)
                </td>
                <td>
                    @Html.Label("Keywords")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Keywords, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Keywords)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Title)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Title)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateTitle
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    @Html.LabelFor(model => model.PublisherUrl)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherUrl)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateURL
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Address")
                </td>
                <td colspan="3">
                    @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Address)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Description")
                </td>
                <td colspan="3">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    @*  <script type="text/javascript">CKEDITOR.replace('PublisherDescription')</script>*@
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Meta Description")
                </td>
                <td colspan="3" style="text-align: right;">
                    @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control" })
                    @*    <script type="text/javascript">CKEDITOR.replace('PublisherMetaDescription')</script>*@
                    @Html.ValidationMessageFor(model => model.MetaDescription)
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </p>
                </td>
            </tr>
        </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExcellentMarketResearch/Areas/Admin/Views/Publisher/PublisherDelete.cshtml
@model ExcellentMarketResearch.Areas.Admin.Models.ViewModel.PublisherVM
@{
    ViewBag.Title = "PublisherDelete";
}

<h2>PublisherDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PublisherId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LongDescription)
        </th>
           <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Keywords)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(item => item.PublisherId)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherName)
        </td>
        <td>
            @Html.DisplayFor(item => item.ContactName)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherContactNumber)
        </td>
        <td>
            @Html.DisplayFor(item => item.Address)
        </td>
        <td>
            @Html.DisplayFor(item => item.Title)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherUrl)
        </td>
        <td>
            @Html.DisplayFor(item => item.LongDescription)
        </td>
        <td>
             @Html.DisplayFor(item => item.ShortDescription)
        </td>
        <td>
            @Html.DisplayFor(item => item.MetaDescription)
        </td>
        <td>
            @Html.DisplayFor(item => item.Keywords)
        </td>
        <td>
            @Html.DisplayFor(item => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(item => item.ModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(item => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(item => item.ModifiedDate)
        </td>
    </tr>
</table>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ExcellentMarketResearch/Areas/Admin/Views/Publisher/PublisherDetails.cshtml
@model ExcellentMarketResearch.Areas.Admin.Models.ViewModel.PublisherVM
@{
    ViewBag.Title = "PublisherDetails";
 }
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PublisherId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublisherUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LongDescription)
        </th>
           <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Keywords)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(item => item.PublisherId)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherName)
        </td>
        <td>
            @Html.DisplayFor(item => item.ContactName)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherContactNumber)
        </td>
        <td>
            @Html.DisplayFor(item => item.Address)
        </td>
        <td>
            @Html.DisplayFor(item => item.Title)
        </td>
        <td>
            @Html.DisplayFor(item => item.PublisherUrl)
        </td>
        <td>
            @Html.DisplayFor(item => item.LongDescription)
        </td>
        <td>
             @Html.DisplayFor(item => item.ShortDescription)
        </td>
        <td>
            @Html.DisplayFor(item => item.MetaDescription)
        </td>
        <td>
            @Html.DisplayFor(item => item.Keywords)
        </td>
        <td>
            @Html.DisplayFor(item => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(item => item.ModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(item => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(item => item.ModifiedDate)
        </td>
    </tr>
</table>
    @Html.ActionLink("Edit", "PublisherEdit", new { id = Model.PublisherId }) 

ExcellentMarketResearch/Areas/Admin/Views/Publisher/PublisherEdit.cshtml
@model ExcellentMarketResearch.Areas.Admin.Models.ViewModel.PublisherVM
@{
    ViewBag.Title = "PublisherEdit";
}
<style type="text/css">
    .table tbody tr td {
        border-top: none;
    }
    .field-validation-error {
        color:red;
    }
</style>
@using (Html.BeginForm("PublisherEdit","Publisher",FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model=>model.PublisherId)
    @Html.HiddenFor(model=>model.CreatedBy)
    @Html.HiddenFor(model=>model.CreatedDate)

        <table class="table" style="text-align:right; width: 80%;margin-top:50px">
            <tr>
                <td>
                    @Html.Label("Company Name")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherName)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateCompanyName
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    @Html.Label("Contact Name")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ContactName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Contact Number")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherContactNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherContactNumber)
                </td>
                <td>
                    @Html.Label("Keywords")
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Keywords, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Keywords)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Title)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Title)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateTitle
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    @Html.LabelFor(model => model.PublisherUrl)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PublisherUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherUrl)
                    <table>
                        <tr>
                            <td style="color: red">
                                @ViewBag.DuplicateURL
                            </td>
                        </tr>
                    </table>
                </td>

            </tr>
            <tr>
                <td>
                    @Html.Label("Address")
                </td>
                <td colspan="3">
                    @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Address)
                </td>

            </tr>
            <tr>

                <td>
                    @Html.Label("Long Description")
                </td>
                <td colspan="3">
                    @Html.TextAreaFor(model => model.LongDescription, new { @class = "form-control" })
                    @*  <script type="text/javascript">CKEDITOR.replace('PublisherDescription')</script>*@
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>

            <tr>

                <td>
                    @Html.Label("Long Description")
                </td>
                <td colspan="3">
                    @Html.TextAreaFor(model => model.ShortDescription, new { @class = "form-control" })
                    @*  <script type="text/javascript">CKEDITOR.replace('PublisherDescription')</script>*@
                    @Html.ValidationMessageFor(model => model.ShortDescription)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.Label("Meta Description")
                </td>
                <td colspan="3" style="text-align: right;">
                    @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control" })
                    @*    <script type="text/javascript">CKEDITOR.replace('PublisherMetaDescription')</script>*@
                    @Html.ValidationMessageFor(model => model.MetaDescription)
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </p>
                </td>
            </tr>
        </table>
}

<div>
    @Html.ActionLink("Back to List", "PublisherIndex")
</div>

ExcellentMarketResearch/Areas/Admin/Views/Publisher/PublisherIndex.cshtml
@model IEnumerable<ExcellentMarketResearch.Models.PublisherMaster>
@{
    ViewBag.Title = "PublisherIndex";
}

<h2>Publisher Index</h2>

<p>
    @Html.ActionLink("Create New", "PublisherCreate")
</p>

<table class="table table-bordered">
    <tr>
        <th>PublisherId
        </th>
        <th>CompanyName
        </th>
        <th>ContactName
        </th>
        <th>ContactNumber
        </th>
        <th>Address
        </th>
      
        <th>PublisherUrl
        </th>
        <th>Short Description
        </th>
        <th>
            Long Description
        </th>
        <th>
           MetaDescription
        </th>
        <th>
         Keywords
        </th>
        @* <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>*@
        <th>Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.publisherUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LongDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MetaDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Keywords)
            </td>
            @* <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDate)
        </td>*@
            <td>
            @Html.ActionLink("Edit", "PublisherEdit", new { id = item.PublisherId }) |
            @Html.ActionLink("Details", "PublisherDetails", new { id = item.PublisherId }) |
            @Html.ActionLink("Delete", "PublisherDelete", new { id = item.PublisherId })
            </td>
        </tr>
    }

</table>